version: "3.8"

services:
  poll-telegram-bot:
    build:
      context: .
    command: poll-telegram-bot -t ${TOKEN} -m ${MODE} -y ${YAML_FILE}
    volumes:
      - "poll_tg_bot_data:/usr/share/poll-telegram-bot/data"

volumes:
  poll_tg_bot_data: